[package]
name = "paprs-math"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pest = "2.7.6"
pest_derive = "2.7.6"
rusttype = "0.9.3"
chrono = "0.4.31"
lazy_static = "1.4.0"
